[db]
url = "postgres://srdown:srdown@localhost:5432/srdown"
schema = "public"
max_connections = 10
sqlx_logging = false

[sync]
max_timeout = 1.0
serve_wait_time = 10.0

[sync.fast]
start_id = 76859
end_id = 1321698
worker_count = 10
worker_size = 10

[serve]
host_with_port = "0.0.0.0:10002"
db_max_connect = 10
enable = false
resync_token = "Its a pretty looong token to keep you safe"
# 10_000ms
refresh_interval = 10_000
