//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::SaveType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "main_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub save_id: i32,
    pub save_type: SaveType,
    pub blake_hash: String,
    pub len: i64,
    pub short_data: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::long_data::Entity")]
    LongData,
}

impl Related<super::long_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LongData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
